name: socialapp
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0
  autoscale_tabbarview: ^1.0.2
  bloc: ^8.1.1
  carousel_slider: ^4.2.1
  chat_bubbles: ^1.5.0
  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  dotted_border: ^2.0.0+3
  easy_stepper: ^0.8.3
  shimmer: ^3.0.0
  flutter_bloc: ^8.1.2
  flutter_screenutil: ^5.9.0
  fluttertoast: ^8.2.1
  font_awesome_flutter: ^10.5.0
  grouped_list: ^5.1.2
  hexcolor: ^3.0.1
  image_picker: ^1.0.6
  intl: ^0.18.1
  otp_text_field: ^1.1.3
  shared_preferences: ^2.1.0
  file_picker: ^5.5.0
  voice_message_package: ^1.0.41
  url_launcher: ^6.1.14
  dio_cookie_manager: ^3.1.1
  cookie_jar: ^4.0.8
  country_pickers: ^2.0.0
  cached_network_image: ^3.3.0
  socket_io_client: ^2.0.3+1
  intl_phone_field: ^3.2.0
  liquid_pull_to_refresh: ^3.0.1
  internet_connection_checker: ^1.0.0+1
  flutter_advanced_drawer: ^1.3.5 
  

  #Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.14.0 
  firebase_storage: ^11.6.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
