// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk6O0HWijKMGXrRFubti87B4p6B3BcZCg',
    appId: '1:843545509036:web:5283a152e7d6103a803309',
    messagingSenderId: '843545509036',
    projectId: 'social-app-d3680',
    authDomain: 'social-app-d3680.firebaseapp.com',
    storageBucket: 'social-app-d3680.appspot.com',
    measurementId: 'G-QN8097GW63',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGy8xo1fRmGQzT0dll4MI0A4VpkTDcE-0',
    appId: '1:843545509036:android:82a7472550c51eb5803309',
    messagingSenderId: '843545509036',
    projectId: 'social-app-d3680',
    storageBucket: 'social-app-d3680.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCujV7vv5_Sb_u-2hBSslyBea_-S821xUA',
    appId: '1:843545509036:ios:084d25dd4fcd07bb803309',
    messagingSenderId: '843545509036',
    projectId: 'social-app-d3680',
    storageBucket: 'social-app-d3680.appspot.com',
    iosBundleId: 'com.example.socialapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCujV7vv5_Sb_u-2hBSslyBea_-S821xUA',
    appId: '1:843545509036:ios:cde677a69c465329803309',
    messagingSenderId: '843545509036',
    projectId: 'social-app-d3680',
    storageBucket: 'social-app-d3680.appspot.com',
    iosBundleId: 'com.example.socialapp.RunnerTests',
  );
}
